### ISSUE TITLE
Schema Scripting for Initialization

### ISSUE THREAD

**Issue by evandana** [evandana/keep-ahope#100]
- [x] Ensure that the schema can be automatically set up on installation
- [x] Provide any necessary documentation

**Comment by pandathegiant** [comment]
https://github.com/evandana/keep-ahope-gcp/pull/7

Documentation-wise: schema (i.e. class) creation is not visible to end-user, so no need to document in end-user oriented documentation.  Code is commented in place wherever necessary and therefore should be self-explanatory.
