### ISSUE TITLE
[GCP] Resolve the Master Key Error.

### ISSUE THREAD

**Issue by evandana** [evandana/keep-ahope#116]
Currently Dashboard, the init code, and Parse server only share the master key if they are from the same instance.  As a result, if a request from Dashboard (or init code) is routed to a different instance, the master key is invalid.  Need a strategy and a new design to handle this situation.

**Comment by pandathegiant** [comment]
Changes planned:

- Database init code will not use the public URL of the parse server; instead, use localhost to access Parse server, which is guaranteed to be in the same instance.

 - In order for the Dashboard to have a valid master key, we need to further do the followings:

    - Instead of generating a master key at the start time of each instance, as it has been the case, master key generation will be based on a service version id and a random number generated at build time of this version.  Hence, once a version is built, the master key is determined and will not change.

    - Dashboard's Parse URL will be specific to a version, so it only connects to a version where itself is originated from.

**Comment by pandathegiant** [comment]
The PR (https://github.com/evandana/keep-ahope-gcp/pull/8) that should fix it has been merged. Closing it.
