### ISSUE TITLE
[GCP] Resolve Initialization Flow

### ISSUE THREAD

**Issue by evandana** [evandana/keep-ahope#117]
As of now, we have moved the database initialization code from running every time an instance goes up to only when an endpoint is hit.  While it prevents flooding/overloading the back-end, it is a security risk (DoS) and could cause unnecessary operation cost.

Need to refactor it so that the initialization code runs only when a new version is deployed for the first time.  Ideally, an instance of old version (in case it is brought up) should not run init code if it has been initialized by a newer version.

**Comment by pandathegiant** [comment]
The PR (https://github.com/evandana/keep-ahope-gcp/pull/8) that should fix it has been merged. Closing it.
