### ISSUE TITLE
Update display of UUID in Search Box And all other locations

### ISSUE THREAD

**Issue by evandana** [evandana/keep-ahope#152]
Add spaces (or slashes) and change font (to separate 0 and O)

LOCATIONS
- Header search bar
- Search context
- Search results

CURRENT
- KRDN051886MOM

IDEAL OPTIONS
- `KRDN 05 18 86 MOM`
- `KRDN 05/18/86 MOM`

![image](https://user-images.githubusercontent.com/857676/64909584-2eeddb00-d6dc-11e9-8d02-942c1ff02a7b.png)

**Comment by danielljohnson** [comment]
Changed to a small as compared to #153, there was a lot more to this one.
