### ISSUE TITLE
On Logout unset the user in the app

### ISSUE THREAD

**Issue by evandana** [evandana/keep-ahope#17]

**Comment by payne-chris-r** [comment]
Jay to merge later today for updated code-set

**Comment by payne-chris-r** [comment]
I'm not sure if this is exactly what you were going for, but I've added a page refresh in the event on sign out. I'd imagine that will do what we're looking for (as that was the console log TODO that I removed), but I'm not super familiar with how hard redux holds onto cached/store data. If there is more to this than just refreshing the page, or we don't want a page refresh and just want to remove the user from the store we can do that too.

**Comment by payne-chris-r** [comment]
https://github.com/evandana/keep-ahope/commit/638db08513a09335ee265c54f8becd72a5aa61af
