### ISSUE TITLE
Clicking link to /contact/abc123/intake from /contact should deep link without a login spinner

### ISSUE THREAD

**Issue by evandana** [evandana/keep-ahope#19]
Steps to reproduce:

- Go to /contact
- Click on a link for /contact/abc123/intake (or similar)
- Notice that the login spinner appears

This should be done so the login spinner does not appear when already logged in and navigating between routes

**Comment by payne-chris-r** [comment]
Unable to reproduce given new code. Close @evandana ?

**Comment by evandana** [comment]
Unable to reproduce now that new code is in
