### ISSUE TITLE
Determine bounds for sliders and add N/A as default

### ISSUE THREAD

**Issue by camden-hill** [evandana/keep-ahope#31]
Sliders already in place on Camden's intake form branch, but do not have the appropriate bounds, nor do they include N/A as default/option.

**Comment by payne-chris-r** [comment]
👀 at this 
https://v0.material-ui.com/#/components/slider

**Comment by payne-chris-r** [comment]
Can't add 'N/A' as default to slider as far as I can tell, 'cause I think it needs to be a number. Thinking about adding a [ x ] N/A option?

**Comment by ahulab** [comment]
hey, what's your progress on this? checkout the most recent changes to the slider in #36, I think they cover this
