### ISSUE TITLE
Ensure that questions on intake form match those requested on Excel from AHOPE

### ISSUE THREAD

**Issue by camden-hill** [evandana/keep-ahope#32]
Most of the fields are there--many of them were created before I (Camden) saw the Excel form, so they may need to be rearranged, and others will certainly need to be added to ensure we're capturing all information.

**Comment by ahulab** [comment]
#50 closes this

**Comment by ahulab** [comment]
@evandana can we talk about closing this today at our meeting?

**Comment by evandana** [comment]
@ahulab completed this over the past weekend
