### ISSUE TITLE
Schema Initialization

### ISSUE THREAD

**Issue by evandana** [evandana/keep-ahope#63]
- [ ] Create `admin` role
- [ ] Create `basic` role
- [ ] Create all classes and add ACLs (Access Control Lists)
- [ ] Ensure this would work for fresh environments

Needs a lot of updating

**Comment by pandathegiant** [comment]
This issue is a duplicate of and superceded by https://github.com/evandana/keep-ahope/issues/109 and https://github.com/evandana/keep-ahope/issues/100.
