### ISSUE TITLE
Deploy UI and GCP Repo Facilitation

### ISSUE THREAD

**Issue by evandana** [evandana/keep-ahope#67]
- [x] Deploy UI  repo
- [x] Deploy GCP repo (server)
- [ ] Document process
- [x] Automate as much as possible

May require prefixing ui and server as such (e.g. `fontend`.keep-ahope.appspot.com `backend`.keep-ahope.appspot.com)

**Comment by pandathegiant** [comment]
Process related to this part of automation is described in the [install instructions](https://github.com/evandana/keep-ahope/wiki/Installation-Instructions).

In addition a [Pull Request](https://github.com/evandana/keep-ahope/pull/119) has been created to further automate the build and deployment of the front end code.
